version: '3.3'
services:
  registry:
    container_name: standalone-registry
    image: registry:2
    ports:
      - 5000:5000
    environment:
      REGISTRY_AUTH_TOKEN_AUTOREDIRECT: "false"
      REGISTRY_AUTH_TOKEN_REALM: http://192.168.0.10:5100/docker/auth/token
      REGISTRY_AUTH_TOKEN_SERVICE: http://localhost:5000
      REGISTRY_AUTH_TOKEN_ISSUER: http://192.168.0.10:5100
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certs/registry-auth.crt
    volumes:
      - ./registry-auth2.crt:/certs/registry-auth.crt
#      - /path/data:/var/lib/registry
#      - /path/auth:/auth